---
abstract: 'Better SQL Generation Through Perl'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  DBI: 0
  Fey::Test: 0.05
  File::Temp: 0
  Test::MockObject: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102345, CPAN::Meta::Converter version 2.101670'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fey
requires:
  Exception::Class: 0
  Exporter: 0
  List::AllUtils: 0
  Moose: 0.90
  MooseX::Params::Validate: 0.08
  MooseX::Role::Parameterized: 0.04
  MooseX::SemiAffordanceAccessor: 0.03
  MooseX::StrictConstructor: 0.07
  MooseX::Types: 0
  Scalar::Util: 0
  Task::Weaken: 0.99
  Tie::IxHash: 0
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Fey
  repository: http://hg.urth.org/hg/Fey
version: 0.38
